# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: Victoria.Victoria
PackageVersion: 5.37
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
